### ISSUE TITLE
SQL error when trying to update DB schema

### ISSUE THREAD

**Issue by ttafet** [Compuskills-Jerusalem/shuk-routing#6]
@ykosbie I tried to update the DB, but I got this error.

System.Data.SqlClient.SqlException
  HResult=0x80131904
  **Message=Unknown object type 'dbo' used in a CREATE, DROP, or ALTER statement.**
  Source=.Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at shuk_routing.Build_Database.Main(String[] args) in C:\Users\USER\source\repos\shuk-routing\shuk-routing\Build_Database.cs:line 46

**Comment by ykopstein** [comment]
@Jatudrei You have an error on line 24 of your build script.  You put the `dbo.` before `TABLE` instead of before the table name.

**Comment by ykahan** [comment]
@ykosbie 

Good to know about.  Thank you.

For some reason, I didn't receive an email notification of your comments.  I am "subscribed," so I should be receiving it...but there I (don't) have it.  :(
